# Generated by Django 4.1.1 on 2022-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityFeed",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("textContent", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
